#!/bin/bash
touch ls_cwd_content echo "total 60
drwxrwxr-x 2 vagrant vagrant 4096 Sep 13 01:02 .
drwxrwxr-x 6 vagrant vagrant 4096 Sep 12 18:23 ..
-rwxrw-r-- 1 vagrant vagrant   32 Sep 12 20:52 0-hello_world
-rw-rw-r-- 1 vagrant vagrant   13 Sep 12 19:48 0-hello_world~
-rwxrw-r-- 1 vagrant vagrant   25 Sep 12 21:10 1-confused_smiley
-rwxrw-r-- 1 vagrant vagrant   25 Sep 12 20:55 1-confused_smiley~
-rwxrw-r-- 1 vagrant vagrant   28 Sep 12 21:38 2-hellofile
-rwxrw-r-- 1 vagrant vagrant   39 Sep 12 21:42 3-twofiles
-rwxrw-r-- 1 vagrant vagrant   29 Sep 12 21:45 4-lastlines
-rwxrw-r-- 1 vagrant vagrant   29 Sep 12 21:47 5-firstlines
-rwxrw-r-- 1 vagrant vagrant   40 Sep 12 23:56 6-third_line
-rw-rw-r-- 1 vagrant vagrant   12 Sep 12 23:46 6-third_line~
-rwxrw-r-- 1 vagrant vagrant   86 Sep 13 00:49 7-file
-rw-rw-r-- 1 vagrant vagrant   40 Sep 13 01:02 8-cwd_state
-rw-rw-r-- 1 vagrant vagrant  727 Sep 12 23:50 iacta"
