#!/usr/bin/env bash
# /redirect_me is redirecting to another page
apt-get update
apt-get -y install nginx
sed -ie "s/^server {$/server {\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/g" /etc/nginx/sites-available/default
service nginx restart
