#!/usr/bin/env bash
# /redirect_me is redirecting to another page
apt-get update
apt-get -y install nginx
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '45 i \\terror_page 404 /404.html;' /etc/nginx/sites-available/default
service nginx restart
