#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.6
apt-get update
apt-get -y install haproxy=1.6.\*
echo -e 'ENABLED=1' >> /etc/default/haproxy
echo -e '
frontend http-in
\tmode http
\tbind *:80
\tdefault_backend web_servers

backend web_servers
\tbalance roundrobin
\tserver 2316-web-01 34.73.89.226
\tserver 2316-web-02 18.212.230.41
' >> /etc/haproxy/haproxy.cfg
service haproxy restart
