#!/usr/bin/env bash
# bash script that creates a file, displays, and deletes the file
su echo $$ > /var/run/holbertonscript.pid
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/holbertonscript.pid; exit' SIGTERM SIGQUIT
while true
do
	echo "To infinity and beyond"
	sleep 2
done
