#!/usr/bin/env bash
# This script is displaying back luck from China for the 4th iteration, bad luck
# from Japan for the 9th iteration, and bad luck from Italy for the 17th iter.
counter=1
while [ $counter -le 20 ]
do
    echo $counter
    case $counter in
	4)
	    echo -n bad luck from China ;;
	9)
	    echo -n bad luck from Japan ;;
	17)
	    echo -n bad luck from Italy ;;
    esac
    ((counter++))
done
