#!/usr/bin/env bash
#  a Bash script that configures an Ubuntu server
cp /etc/hosts ~/hosts_copy
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts_copy
echo "8.8.8.8 facebook.com" >> ~/hosts_copy
cp -f ~/hosts_copy /etc/hosts
