#!/usr/bin/env bash
# this script debugs a container and changes user and port
pkill -f apache2
chown nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
su nginx service nginx start
